const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORAGE={recipes:'rdc_recipes_v2',shopping:'rdc_shopping_v2',theme:'rdc_theme_v1'};
let recipes=load(STORAGE.recipes,[]),shopping=load(STORAGE.shopping,[]),deferredInstallPrompt=null;
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function uid(){return `${Date.now()}-${Math.random().toString(16).slice(2)}`}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.remove('show'),2200)}
function save(){localStorage.setItem(STORAGE.recipes,JSON.stringify(recipes));localStorage.setItem(STORAGE.shopping,JSON.stringify(shopping));renderAll()}
function go(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.go===v));history.replaceState(null,'',`#${v}`);window.scrollTo({top:0,behavior:'smooth'})}

document.addEventListener('click',e=>{const g=e.target.closest('[data-go]');if(g)return go(g.dataset.go);const c=e.target.closest('[data-close-dialog]');if(c)return c.closest('dialog')?.close();const n=e.target.closest('[data-action="new-recipe"]');if(n)return openEditor();const cat=e.target.closest('[data-category]');if(cat){go('pesquisar');return searchMealsByCategory(cat.dataset.category)}const q=e.target.closest('[data-search]');if(q){$('#searchInput').value=q.dataset.search;return doSearch(q.dataset.search)}});

function card(r,external=false){return `<article class="recipe-card"><div class="recipe-media">${r.image?`<img src="${esc(r.image)}" alt="${esc(r.name)}" loading="lazy">`:'<div class="recipe-placeholder">🍽️</div>'}${external?'':`<button class="favorite-btn" onclick="toggleFavorite('${r.id}')">${r.favorite?'♥':'♡'}</button>`}</div><div class="recipe-body"><div class="recipe-meta">${r.category?`<span class="pill">${esc(r.category)}</span>`:''}${r.time?`<span class="pill">⏱ ${esc(r.time)}</span>`:''}${r.servings?`<span class="pill">👥 ${esc(r.servings)}</span>`:''}</div><h3>${esc(r.name)}</h3>${r.description?`<p>${esc(r.description.slice(0,115))}${r.description.length>115?'…':''}</p>`:''}<div class="recipe-actions"><button class="btn secondary" onclick="${external?`openExternal('${r.externalId}')`:`openRecipe('${r.id}')`}">Ver receita</button>${external?`<button class="btn primary" onclick="saveExternal('${r.externalId}')">Guardar</button>`:`<button class="btn" onclick="editRecipe('${r.id}')">Editar</button>`}</div></div></article>`}

function renderAll(){
  $('#statRecipes').textContent=recipes.length;$('#statFavorites').textContent=recipes.filter(r=>r.favorite).length;$('#statShopping').textContent=shopping.filter(i=>!i.done).length;
  const recent=[...recipes].sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)).slice(0,3);$('#recentRecipes').innerHTML=recent.length?recent.map(r=>card(r)).join(''):'<div class="empty" style="grid-column:1/-1"><div>🍴</div><h3>Ainda sem receitas</h3><p>Guarda uma receita online ou cria uma receita vossa.</p></div>';
  renderMy();const favs=recipes.filter(r=>r.favorite);$('#favoriteRecipes').innerHTML=favs.map(r=>card(r)).join('');$('#favEmpty').classList.toggle('hidden',favs.length>0);renderShopping()
}
function renderMy(){const term=($('#mySearch').value||'').trim().toLowerCase(),cat=$('#myCategory').value||'';const f=recipes.filter(r=>(!term||`${r.name} ${r.description||''} ${(r.ingredients||[]).map(i=>i.name).join(' ')}`.toLowerCase().includes(term))&&(!cat||r.category===cat));$('#myRecipes').innerHTML=f.map(r=>card(r)).join('');$('#myEmpty').classList.toggle('hidden',f.length>0||recipes.length>0)}
$('#mySearch').addEventListener('input',renderMy);$('#myCategory').addEventListener('change',renderMy);
function toggleFavorite(id){const r=recipes.find(x=>x.id===id);if(!r)return;r.favorite=!r.favorite;r.updatedAt=Date.now();save();toast(r.favorite?'Adicionada aos favoritos':'Removida dos favoritos')}

function normalizeMeal(m){const ingredients=[];for(let i=1;i<=20;i++){const name=(m[`strIngredient${i}`]||'').trim(),qty=(m[`strMeasure${i}`]||'').trim();if(name)ingredients.push({name,qty})}const steps=(m.strInstructions||'').split(/\r?\n+/).map(s=>s.trim()).filter(Boolean);return{externalId:m.idMeal,name:m.strMeal,image:m.strMealThumb,category:m.strCategory||'Online',area:m.strArea||'',description:m.strInstructions||'',ingredients,steps:steps.length?steps:[m.strInstructions||'Preparação não disponível.'],sourceUrl:m.strSource||''}}
async function doSearch(q){q=(q||'').trim();if(!q){$('#searchStatus').textContent='Escreve o nome de uma receita.';return}$('#searchStatus').textContent='A pesquisar…';$('#searchResults').innerHTML='';try{const d=await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=${encodeURIComponent(q)}`).then(r=>r.json());const meals=(d.meals||[]).map(normalizeMeal);window.__online=Object.fromEntries(meals.map(m=>[m.externalId,m]));$('#searchStatus').textContent=meals.length?`${meals.length} receita(s) encontrada(s).`:'Não encontrei receitas com esse nome.';$('#searchResults').innerHTML=meals.map(m=>card(m,true)).join('')}catch{$('#searchStatus').textContent='Não foi possível pesquisar agora. Confirma a ligação à internet.'}}
async function searchMealsByCategory(cat){$('#searchInput').value=cat;$('#searchStatus').textContent='A pesquisar categoria…';try{const d=await fetch(`https://www.themealdb.com/api/json/v1/1/filter.php?c=${encodeURIComponent(cat)}`).then(r=>r.json());const ids=(d.meals||[]).slice(0,12).map(x=>x.idMeal);const all=await Promise.all(ids.map(id=>fetch(`https://www.themealdb.com/api/json/v1/1/lookup.php?i=${id}`).then(r=>r.json())));const meals=all.map(x=>normalizeMeal(x.meals[0]));window.__online=Object.fromEntries(meals.map(m=>[m.externalId,m]));$('#searchStatus').textContent=`${meals.length} receita(s) encontrada(s).`;$('#searchResults').innerHTML=meals.map(m=>card(m,true)).join('')}catch{$('#searchStatus').textContent='Não foi possível carregar esta categoria.'}}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();doSearch($('#searchInput').value)});
async function getOnline(id){if(window.__online?.[id])return window.__online[id];const d=await fetch(`https://www.themealdb.com/api/json/v1/1/lookup.php?i=${id}`).then(r=>r.json());return normalizeMeal(d.meals[0])}
async function openExternal(id){showRecipe(await getOnline(id),true)}
async function saveExternal(id){const r=await getOnline(id);if(recipes.some(x=>x.source==='online'&&x.externalId===id))return toast('Esta receita já está guardada.');recipes.unshift({id:uid(),name:r.name,image:r.image,category:r.category,description:r.description,ingredients:r.ingredients,steps:r.steps,time:'',servings:'',difficulty:'',notes:'',favorite:false,source:'online',externalId:id,sourceUrl:r.sourceUrl,createdAt:Date.now(),updatedAt:Date.now()});save();toast('Receita guardada em Minhas Receitas.')}
function openRecipe(id){const r=recipes.find(x=>x.id===id);if(r)showRecipe(r,false)}
function showRecipe(r,external){const ing=(r.ingredients||[]).map(i=>`<li><strong>${esc(i.qty||'')}</strong> ${esc(i.name||'')}</li>`).join(''),steps=(r.steps||[]).map(s=>`<li>${esc(s)}</li>`).join('');$('#recipeDetail').innerHTML=`<div class="detail-hero">${r.image?`<img src="${esc(r.image)}" alt="${esc(r.name)}">`:'<div class="recipe-placeholder">🍽️</div>'}</div><div class="detail-top"><span class="eyebrow">${external?'RECEITA ONLINE':'RECEITA GUARDADA'}</span><h2>${esc(r.name)}</h2><div class="recipe-meta">${r.category?`<span class="pill">${esc(r.category)}</span>`:''}${r.area?`<span class="pill">${esc(r.area)}</span>`:''}${r.time?`<span class="pill">⏱ ${esc(r.time)}</span>`:''}${r.servings?`<span class="pill">👥 ${esc(r.servings)}</span>`:''}</div><div class="detail-actions">${external?`<button class="btn primary" onclick="saveExternal('${r.externalId}')">Guardar nas minhas receitas</button>`:`<button class="btn primary" onclick="addRecipeToShopping('${r.id}')">Adicionar ingredientes às compras</button><button class="btn secondary" onclick="shareRecipe('${r.id}')">Partilhar</button><button class="btn secondary" onclick="editRecipe('${r.id}');document.querySelector('#recipeDialog').close()">Editar</button><button class="btn secondary" onclick="deleteRecipe('${r.id}')">Apagar</button>`}</div></div><div class="detail-grid"><div><h3>Ingredientes</h3><ul class="ingredient-list">${ing||'<li>Sem ingredientes registados.</li>'}</ul></div><div><h3>Preparação</h3><ol class="steps-list">${steps||'<li>Sem passos registados.</li>'}</ol></div></div>${r.notes?`<div style="margin-top:24px"><h3>Notas</h3><p>${esc(r.notes)}</p></div>`:''}`;$('#recipeDialog').showModal()}

function openEditor(r=null){$('#recipeForm').reset();$('#recipeId').value=r?.id||'';$('#editorTitle').textContent=r?'Editar receita':'Nova receita';$('#rName').value=r?.name||'';$('#rCategory').value=r?.category||'Outras';$('#rDescription').value=r?.description||'';$('#rTime').value=r?.time||'';$('#rServings').value=r?.servings||4;$('#rDifficulty').value=r?.difficulty||'Fácil';$('#rImage').value=r?.image||'';$('#rNotes').value=r?.notes||'';$('#ingredientsEditor').innerHTML='';(r?.ingredients?.length?r.ingredients:[{name:'',qty:''}]).forEach(addIngredientRow);$('#stepsEditor').innerHTML='';(r?.steps?.length?r.steps:['']).forEach(addStepRow);$('#editorDialog').showModal()}
function editRecipe(id){const r=recipes.find(x=>x.id===id);if(r)openEditor(r)}
function addIngredientRow(item={name:'',qty:''}){const d=document.createElement('div');d.className='editor-row';d.innerHTML=`<input class="ing-name" placeholder="Ingrediente" value="${esc(item.name||'')}"><input class="ing-qty" placeholder="Quantidade" value="${esc(item.qty||'')}"><button type="button" class="remove-row">×</button>`;$('.remove-row',d).onclick=()=>d.remove();$('#ingredientsEditor').appendChild(d)}
function addStepRow(step=''){const d=document.createElement('div');d.className='editor-row editor-step';d.innerHTML=`<div class="step-num">${$('#stepsEditor').children.length+1}</div><input class="step-text" placeholder="Descreve este passo…" value="${esc(step)}"><button type="button" class="remove-row">×</button>`;$('.remove-row',d).onclick=()=>{d.remove();$$('.step-num',$('#stepsEditor')).forEach((n,i)=>n.textContent=i+1)};$('#stepsEditor').appendChild(d)}
$('#addIngredientBtn').onclick=()=>addIngredientRow();$('#addStepBtn').onclick=()=>addStepRow();
$('#recipeForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#recipeId').value,ingredients=$$('#ingredientsEditor .editor-row').map(row=>({name:$('.ing-name',row).value.trim(),qty:$('.ing-qty',row).value.trim()})).filter(i=>i.name),steps=$$('#stepsEditor .step-text').map(i=>i.value.trim()).filter(Boolean),data={name:$('#rName').value.trim(),category:$('#rCategory').value,description:$('#rDescription').value.trim(),time:$('#rTime').value.trim(),servings:$('#rServings').value,difficulty:$('#rDifficulty').value,image:$('#rImage').value.trim(),ingredients,steps,notes:$('#rNotes').value.trim(),updatedAt:Date.now()};if(id){const i=recipes.findIndex(r=>r.id===id);recipes[i]={...recipes[i],...data}}else recipes.unshift({id:uid(),favorite:false,source:'local',createdAt:Date.now(),...data});save();$('#editorDialog').close();go('minhas');toast('Receita guardada.')});
function deleteRecipe(id){if(!confirm('Apagar esta receita?'))return;recipes=recipes.filter(r=>r.id!==id);save();$('#recipeDialog').close();toast('Receita apagada.')}

function addRecipeToShopping(id){const r=recipes.find(x=>x.id===id);if(!r)return;(r.ingredients||[]).forEach(i=>{if((i.name||'').trim())shopping.push({id:uid(),name:i.name.trim(),qty:i.qty||'',done:false,recipe:r.name,createdAt:Date.now()})});save();toast('Ingredientes adicionados à lista de compras.')}
$('#shoppingForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#shopName').value.trim();if(!name)return;shopping.push({id:uid(),name,qty:$('#shopQty').value.trim(),done:false,recipe:'',createdAt:Date.now()});$('#shoppingForm').reset();save()});
function renderShopping(){$('#shoppingList').innerHTML=shopping.map(i=>`<div class="shop-row ${i.done?'done':''}"><input type="checkbox" ${i.done?'checked':''} onchange="toggleShop('${i.id}')"><div class="shop-name"><strong>${esc(i.name)}</strong><small>${esc(i.qty||'')}${i.recipe?` · ${esc(i.recipe)}`:''}</small></div><span>${i.done?'✓':''}</span><button class="shop-delete" onclick="deleteShop('${i.id}')">×</button></div>`).join('');$('#shopEmpty').classList.toggle('hidden',shopping.length>0)}
function toggleShop(id){const i=shopping.find(x=>x.id===id);if(i){i.done=!i.done;save()}}function deleteShop(id){shopping=shopping.filter(i=>i.id!==id);save()}$('#clearBoughtBtn').onclick=()=>{shopping=shopping.filter(i=>!i.done);save()};
async function shareRecipe(id){const r=recipes.find(x=>x.id===id);if(!r)return;const text=`${r.name}\n\nIngredientes:\n${(r.ingredients||[]).map(i=>`- ${i.qty?i.qty+' ':''}${i.name}`).join('\n')}\n\nPreparação:\n${(r.steps||[]).map((s,i)=>`${i+1}. ${s}`).join('\n')}`;try{if(navigator.share)await navigator.share({title:r.name,text});else{await navigator.clipboard.writeText(text);toast('Receita copiada.')}}catch{}}
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');const d=document.body.classList.contains('dark');localStorage.setItem(STORAGE.theme,d?'dark':'light');$('#themeBtn').textContent=d?'☀':'☾'};if(localStorage.getItem(STORAGE.theme)==='dark'){document.body.classList.add('dark');$('#themeBtn').textContent='☀'}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installBtn').classList.add('hidden')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
const initial=(location.hash||'#inicio').slice(1);go(['inicio','pesquisar','minhas','favoritos','compras'].includes(initial)?initial:'inicio');renderAll();
Object.assign(window,{toggleFavorite,openRecipe,editRecipe,openExternal,saveExternal,addRecipeToShopping,toggleShop,deleteShop,shareRecipe,deleteRecipe});
